# Generated by Django 2.1.1 on 2018-09-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='marker',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='mapapp.MarkerModel'),
        ),
    ]
